catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books', views.BookListView.as_view(), name='books'),
    path('book/<uuid:id>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:id>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks', views.LoanedBooksByUserListView.as_view(),
         name='borrowed-books'),
    path('borrowed', views.LibrairianListView.as_view(), name='borrowed'),
    path('book/<uuid:id>/renew', views.renew_book_librairian,
         name='renew-book-librairian'),
    path('author/create', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:id>/update',
         views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:id>/delete',
         views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create', views.CreateBook.as_view(), name='book_create')
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    re_path('admin/', admin.site.urls),
    #re_path('formview/', FormView.as_view(), name='show-form'),
    re_path('catalog/', include('catalog.urls')),
    re_path(r'^$', RedirectView.as_view(url='catalog/', permanent=True),),
    re_path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.STATIC_URL, documnet_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractUser
from datetime import date
# Create your models here.


class User(AbstractUser):
    username = models.CharField(
        max_length=255, null=False, blank=False, unique=True)

    USERNAME_FIELD = 'username'


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="A Unique Identifier for a book")
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField(
        'ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre,  help_text='Select a genre for this book',)
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200, default="")
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        permissions = (
            ('can_mark_returned', 'Set book as returned'),
            ('can_renew', 'Renew a book')
        )
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        from django.urls import reverse
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime
import catalog.models as models
# Write your forms here


class RenewaBookForm(ModelForm):
    class Meta:
        model = models.BookInstance
        fields = ('due_back',)
        label = {'due_back': _('New renewal date')}
        help_text = {'due_back': _(
            'Enter a date between now an 4 weeks (default 3). ')}

    def clean_due_back(self):
        date = self.cleaned_data.get('renewal_date')

        if date < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if date > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        return date


class CreateAuthorForm(ModelForm):
    class Meta:
        model = models.Author
        fields = '__all__'

catalog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book, BookInstance, Genre, Author, BookInstance
from django.views import generic, View
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.contrib import messages
from .forms import RenewaBookForm
import datetime
from django.urls import reverse_lazy
from .forms import CreateAuthorForm


@permission_required('can_renew')
def renew_book_librairian(request, id):
    book_instance = get_object_or_404(BookInstance, id=id)
    print(book_instance)

    if request.method == 'POST':
        form = RenewaBookForm(request.POST)

        if form.is_valid():
            date = form.cleaned_data.get('renewal_date')
            book_instance.due_back = date
            book_instance.save()

            return redirect('borrowed')
    else:
        proposed_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewaBookForm(initial={'due_back': proposed_date})

    context = {'form': form, 'book_instance': book_instance}

    return render(request, 'catalog/book_renew_librarian.html', context)


@login_required
@permission_required(('catalog.can_mark_returned'))
def index(request):
    "View function for home page of site"

    # Generate counts of some of the main objects
    number_books = Book.objects.all().count()
    number_instances = BookInstance.objects.all().count()

    # Available books (ie: status = 'a)
    number_instances_available = BookInstance.objects.filter(
        status__iexact='a').count()
    # All authors

    number_authors = Author.objects.count()

    number_genres = Genre.objects.count()

    # Number of visits to this view, as counted in the session variable
    visits = request.session.get('visits', 0)
    request.session['visits'] = visits+1
    if visits >= 5:
        request.session['visits'] = 0
        request.session.modified = True

    # All genres
    # keys in the context object are variables in template
    context = {
        'number_books': number_books,
        'number_instances': number_instances,
        'number_instances_available': number_instances_available,
        'number_authors': number_authors,
        'number_genres': number_genres,
        'title': 'Home',
        'visits': visits
    }

    return render(request, 'catalog/index.html', context)


class BookListView(LoginRequiredMixin, generic.ListView):
    # login_url = '/accounts/login/'
    redirect_field_name = 'list_of_books'
    permission_required = 'catalog.can_mark_returned'
    # model = Book
    template_name = 'catalog/book_list.html'
    paginate_by = 1
    # queryset = Book.objects.filter(title__icontains='war')

    def get_queryset(self):
        return Book.objects.all()

    # def get_template_names(self):
        # return 'catalog/book_list.html'


class AuthorListView(generic.ListView):
    def get_queryset(self):
        return Author.objects.all()

    def get_template_names(self):
        return 'catalog/author_list.html'

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context['authors'] = 'Authors'
        return context


class AuthorDetailView(generic.DetailView):
    def get_object(self, queryset=None):
        _id = self.kwargs.get('id')
        return get_object_or_404(Author, id=_id)


class BookDetailView(generic.DetailView):

    def get_object(self):
        _id = self.kwargs.get('id')
        return get_object_or_404(Book, id=_id)

    def get_template_names(self):
        return 'catalog/book_detail.html'


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookInstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LibrairianListView(PermissionRequiredMixin, View):
    model = BookInstance
    template_name = 'catalog/librairian_list_borrowed.html'
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

    def get_context_data(self, **kwargs):
        context = {}
        context['bookinstance_list'] = self.get_queryset()
        return context

    def handle_no_permission(self):
        return redirect('index')

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())


@login_required
@permission_required(('catalog.can_mark_returned'))
def librairianListView(request):
    bookinstance_list = BookInstance.objects.filter(
        status__exact='o').order_by('due_back')
    context = {'bookinstance_list': bookinstance_list}
    return render(request, 'catalog/librairian_list_borrowed.html', context)


class AuthorCreate(generic.edit.CreateView):
    model = Author
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(AuthorCreate, self).get_context_data(**kwargs)
        context['title'] = 'Create Author'
        return context


class AuthorUpdate(generic.edit.UpdateView):
    model = Author
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(AuthorUpdate, self).get_context_data(**kwargs)
        context['title'] = 'update '
        return context

    def get_object(self, queryset=None):
        _id = self.kwargs.get('id')
        return get_object_or_404(self.model, id=_id)


class AuthorDelete(generic.edit.DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

    def get_object(self, queryset=None):
        _id = self.kwargs.get('id')
        return get_object_or_404(self.model, id=_id)


class CreateBook(generic.edit.CreateView):
    model = Book
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(CreateBook, self).get_context_data(**kwargs)
        context['title'] = 'Create Book'
        return context

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %} {% block title %}
<title>{{ author|title }}</title>
{% endblock title %} {% block content %}
<p class="h1">{{ author|title }}</p>
<ul>
  <li class="m-2">
    <span style="font-weight: 900;">first name: </span>
    {{ author.first_name|capfirst }} {{ author.last_name|capfirst }}
  </li>
  <li class="m-2">
    <span style="font-weight: 900;">Date of birth: </span>
    {{ author.date_of_birth|date:"M d Y" }}
  </li>
  {% if author.date_of_death %}
  <li class="m-2">
    <span style="font-weight: 900;">Date of death:</span> {{
    author.date_of_death|date:"M d Y" }}
  </li>
  {% endif %}
  <p class="h1">Books wrote by {{ author.first_name }} {{ author.last_name}}</p>
  {% for author_book in author.book_set.all %}
  <div class="row">
    <ul class="list-group col-sm-4">
      <li class="list-group-item">title: {{ author_book.title }}</li>
      <li class="list-group-item">laguage: {{ author_book.language }}</li>
      <li class="list-group-item">isbn: {{ author_book.isbn }}</li>
    </ul>
  </div>
  {% endfor %}
  <p class="mt-4">
    Total book{{ author.book_set.all|pluralize }}
    <span class="badge badge-primary">{{ author.book_set.all.count}}</span>
  </p>
</ul>
{% endblock content %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1> {{title}} </h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% block title %}
<title> {{ authors|title }} </title>
{% endblock title %}
{% block content %}
<h1>Author List</h1>
<ul>
    {% for author in author_list %}
        <li class="m-2">
            <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
        </li>
    {% endfor %}
</ul>


{% endblock content %}

catalog/templates/catalog/bookInstance_list_borrowed_user.html
{% extends "base_generic.html" %} {% block title %}
<title>borrowed-books</title>
{% endblock title %} {% block content %}
<h1 class="h1">Borrowed Books</h1>
{% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'book-detail' bookinst.book.pk %}"
                >{{bookinst.book.title}}</a
                >
                ({{ bookinst.due_back }})
            </li>
        {% endfor %}
    </ul>
{% else %}
<p>There are no books borrowed.</p>
{% endif%} {% endblock content %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %} {% block title %}
<title>{{ book.title }}</title>
{% endblock title %} {% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
<!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
  <h4>Copies</h4>

  {% for copy in book.bookinstance_set.all %}
  <hr />
  <p
    class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}"
  >
    {{ copy.get_status_display }}
  </p>
  {% if copy.status != 'a' %}
  <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
  {% endif %}
  <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
  <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
  {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}


{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
{% endblock content %}
    

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %} {% block title %}
<title>{{ title|upper }}</title>
{% endblock title %} {% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
  {% for book in book_list %}
  <li>
    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
    
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/forms.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{{ title|upper }}</title>
  </head>
  <body>
    <form action="." method="post">
      {% csrf_token %} {{ form.as_p|crispy }}
      <button type="submit">Envoyer</button>
    </form>
  </body>
</html>

catalog/templates/catalog/index.html
{% extends "base_generic.html" %} {% block title %}
<title>{{ title|upper }}</title> {% endblock title %} {% block content %}
<h1>Local Library Home</h1>
<p>
  Welcome to LocalLibrary, a website developed by
  <em>Mozilla Developer Network</em>!
</p>
<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
  <li>
    <strong>Books:</strong>
    <span class="badge badge-primary">{{ number_books }}</span>
  </li>
  <li>
    <strong>Copies:</strong>
    <span class="badge badge-primary">{{ number_instances }}</span>
  </li>
  <li>
    <strong>Copies available:</strong>
    <span class="badge badge-primary">{{ number_instances_available }}</span>
  </li>
  <li>
    <strong>Authors:</strong>
    <span class="badge badge-primary">{{ number_authors }}</span>
  </li>
  <li>
    <strong>Genres:</strong>
    <span class="badge badge-primary">{{ number_genres }}</span>
  </li>
</ul>

<p>
  You have visited this page {{ visits }} {% if visits > 1 %} times {% else %}
  time {% endif %}
</p>
{% endblock %}

catalog/templates/catalog/librairian_list_borrowed.html
{% extends 'base_generic.html' %}

{% block title %}
    {% if user.is_authenticated %}
        <title>{{user.username|upper}}</title>
    {% endif %}
{% endblock title %}

{% block content %}

    <h1 class="h1">Borrowed books</h1>
    {% if user.is_authenticated %}
        
        {% if perms.catalog.can_mark_returned  %}
            
            {% if bookinstance_list %}
                <ul>
                    {% for book in bookinstance_list %}
                    <li>
                        {{ book.book.title }} - <span class="{% if book.is_overdue %} text-danger {% endif %}"> {{ book.due_back }}</span>-
                        {{ book.borrower.username }}
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>no borrowed books</p>
            {% endif %}
    
        {% endif %}
            
    {% endif %}
        
  
{% endblock content %}